### ISSUE TITLE
Sirach 29:16-18

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#13]
These three verses (**Sirach 29:16-18**) appear _inline_ in the TEI file:
```
<ab n="16">Mieux que le bouclier</ab> <ab n="17">et la
lance du héros (puissant),</ab> <ab n="18">elle combattra contre ton ennemi.
</ab>
```
This location is the _sole_ instance where a verse does not begin at the _start_ of the line.

In the USFM file, it became:
```
\v 16 Mieux que le bouclier \v 17 et la lance du héros (puissant), \v 18 elle combattra contre ton ennemi.
```

This is not a problem. The tool to convert USFM to OSIS XML still works.

I merely record the fact because it was _unusual_.

**Comment by MarjorieBurghart** [comment]
Yes, OK, in XML it's not a problem at all. I'll leave it like that, there's no real reason to change it other than how the XML looking prettier, and if I start in this direction I should reformat absolutely every file (to get rid of the insignificant line breaks within verses)
