### ISSUE TITLE
No verse text present in Deuteronomy 27:16

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#2]
**Deuteronomy 27:16** reads:
```
    <ab n="16"></ab>
```
This verse in the English KJV begins, "Cursed _be_ he that setteth light by his father or his mother. ..."

**Comment by MarjorieBurghart** [comment]
I'm afraid this comes from the source, which just skips v. 16 in this chapter: 
http://jesusmarie.free.fr/bible_vigouroux_deuteronome.html
I don't have a hard copy of this Bible at hand. I would be grateful if someone could check what the correct version should be.

**Comment by MarjorieBurghart** [comment]
Judging from the Latin Vulgate text, one would expect something like "Maudit celui qui n'honore pas son père et sa mère, et tout le peuple dira : Amen", but that's my own translation.

**Comment by DavidHaslam** [comment]
Have you tried looking in Google books?
A lot of Public Domain works have been scanned.

**Comment by DavidHaslam** [comment]
Also, now you're aware of the omission, I suggest it would be helpful to report it "upstream" to the webmaster for jesusmarie.free.fr

**Comment by MarjorieBurghart** [comment]
I've just done that (reporting to the source website), but I did not manage to find the same edition on the web. There is a similar one on Archive.org, but it's not the same text.

**Comment by DavidHaslam** [comment]
Try a library search using WorldCat. 
If you find a holding library, you'd need to find a local volunteer to look it up.

**Comment by MarjorieBurghart** [comment]
I'm hoping the initial website owns a copy and will contact me back with the correct version :) 
Pending that, the book should be at the French national library in Paris.

**Comment by DavidHaslam** [comment]
FYI. I've converted your XML files to [USFM format](http://paratext.org/usfm) (as used by Bible translators).
This issue and #1 came to light through this exercise.

If I come across further textual anomalies, I'll add new issues.
cf. Such file format conversions quite often bring a few more things to light.

Have in mind to create a SWORD module that could be used with Bible study apps from [CrossWire](http://crosswire.org/).

**Comment by MarjorieBurghart** [comment]
Thanks for letting me know! Your contribution is much appreciated. 
I created the XML files as a pivot format for further conversions, it's good to know I'm not the only one who has used them :)

**Comment by MarjorieBurghart** [comment]
The webmaster of the original website kindly sent me the text of the verse ("Maudit celui qui n'honore point son père et sa mère ! Et tout le peuple dira : Amen."), and I've just added it to Dt. and committed.

**Comment by DavidHaslam** [comment]
I have just fixed the apostrophe in the added verse.

**Comment by MarjorieBurghart** [comment]
woops, sorry, and thanks :)
