### ISSUE TITLE
Prettifying the TEI XML files?

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#23]
@MarjorieBurghart 

Would you have any objection were I to _prettify_ the 73 TEI XML files?

- XML is neatly indented using tabs
- Whitespace within text is trimmed
- Each verse occupies a single line.

This would make subsequent processing for adding the **note** elements somewhat simpler.

Example in attached Zip file.

[1Cor.pp.xml.zip](https://github.com/MarjorieBurghart/VulgateGlaire/files/1379117/1Cor.pp.xml.zip)

**Comment by MarjorieBurghart** [comment]
No objection! :)

**Comment by DavidHaslam** [comment]
Just done that in the **Prettify** branch of a fresh new fork.

Exception to the "verse per line" layout:
- **Psalms** &ndash; because of the _italics_ markup around the _titles_ or _acrostics_ at the start of **158** verses.
- **Lamentations** &ndash; because of the _italics_ markup around the _acrostics_ at the start of **132** verses.

**Comment by DavidHaslam** [comment]
All but the smaller files will have a "large diff" when you first see the compare for pull request #25
