### ISSUE TITLE
Enhance README.md by linking to the Wikipedia page: Jean-Baptiste Glaire

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#3]
Suggested link is [l'Abbé Glaire](https://en.wikipedia.org/wiki/Jean-Baptiste_Glaire)

**Comment by DavidHaslam** [comment]
Just made this change in the **Editing** branch of my fork.  Pull request to follow.

**Comment by MarjorieBurghart** [comment]
Good idea, thanks, merged.
