### ISSUE TITLE
Text in italics

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#5]
Text in _italics_ uses `<hi rend="italics">`...`</hi>` as the XML markup.

The period (full-stop) at the end of some **canonical Psalm titles** ought to be placed _before_ the `</hi>`.

Structurally, the period is part of the title, and should not be left outside it.
Visually, it makes little difference. 

The only two books where this is necessary are **Psalms** & **Lamentations**.

In the latter, the period terminates the Hebrew letter name for the **acrostics**.

**Comment by DavidHaslam** [comment]
Just made this change in the **Editing** branch of my fork.  Pull request to follow.

**Comment by DavidHaslam** [comment]
Pull request #7

**Comment by MarjorieBurghart** [comment]
Thanks, merged!

**Comment by DavidHaslam** [comment]
See also #19
