### ISSUE TITLE
Psalm 22 versification difference compared to Vulgate

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#9]
During SWORD module build using the **osis2mod** tool, the following was logged:
```
INFO(V11N): Ps.22.7 is not in the Vulg versification. Appending content to Ps.22.6
INFO(WRITE): Appending entry: Ps.22.6: pour que j’habite dans la maison du Seigneur durant de longs jours.  <chapter eID="Ps.22"/>
```

cf.The **Clementine Vulgate** has only 6 verses in **Psalm 22**:
```
Psalms 22:1: Psalmus David. [Dominus regit me, et nihil mihi deerit :/
Psalms 22:2: in loco pascuæ, ibi me collocavit./ Super aquam refectionis educavit me ;/
Psalms 22:3: animam meam convertit./ Deduxit me super semitas justitiæ/ propter nomen suum./
Psalms 22:4: Nam etsi ambulavero in medio umbræ mortis,/ non timebo mala, quoniam tu mecum es./ Virga tua, et baculus tuus,/ ipsa me consolata sunt./
Psalms 22:5: Parasti in conspectu meo mensam/ adversus eos qui tribulant me ;/ impinguasti in oleo caput meum :/ et calix meus inebrians, quam præclarus est !/
Psalms 22:6: Et misericordia tua subsequetur me/ omnibus diebus vitæ meæ ;/ et ut inhabitem in domo Domini/ in longitudinem dierum.] 
```

**Comment by DavidHaslam** [comment]
FIO. After converting the latest **Clementine Vulgate** source text to USFM, at the current stage in my activity, it's marked up as follows:
```
\c 22
\p
\v 1 Psalmus David.
\q Dominus regit me, et nihil mihi deerit :
\q
\v 2 in loco pascu, ibi me collocavit.
\q Super aquam refectionis educavit me ;
\q
\v 3 animam meam convertit.
\q Deduxit me super semitas justiti
\q propter nomen suum.
\q
\v 4 Nam etsi ambulavero in medio umbr mortis,
\q non timebo mala, quoniam tu mecum es.
\q Virga tua, et baculus tuus,
\q ipsa me consolata sunt.
\q
\v 5 Parasti in conspectu meo mensam
\q adversus eos qui tribulant me ;
\q impinguasti in oleo caput meum :
\q et calix meus inebrians, quam prclarus est !
\q
\v 6 Et misericordia tua subsequetur me
\q omnibus diebus vit me ;
\q et ut inhabitem in domo Domini
\q in longitudinem dierum.
```

NB. I expect to replace `\p` by `\d` before verse 1.

For tag descriptions, refer to [ParaTExt/USFM](http://paratext.org/usfm) documentation.

**Comment by DavidHaslam** [comment]
FIO. To understand more about different Bible versifications, visit [Alternate Versification](https://crosswire.org/wiki/Alternate_Versification).

For how Psalms are numbered in different canons, see [Psalms#Numbering](https://en.wikipedia.org/wiki/Psalms#Numbering).

e.g. Psalm 22 in the Vulgate is the well-known **23rd Psalm** in the KJV, etc.

**Comment by MarjorieBurghart** [comment]
OK, I've merged v. 6 and 7 in the Ps.xml file.

**Comment by DavidHaslam** [comment]
Did you check the hard copy?

I'd prefer to keep v7 separate if this accurately reflects a minor versification difference by Glaire himself.

The module build tool took care of appending it.
It's not an error _per se_. Merely a warning.

**Comment by DavidHaslam** [comment]
FIO. Screenshot from [Xiphos](http://xiphos.org/) after I made the SWORD module.

![screenshot 2017-10-09 13 08 36](https://user-images.githubusercontent.com/16325414/31337426-3a59f9a2-acf3-11e7-8451-07c1ba0337a4.png)

**Comment by DavidHaslam** [comment]
FIO. The module **About** window in Xiphos.

![screenshot 2017-10-09 13 11 40](https://user-images.githubusercontent.com/16325414/31337495-83634f54-acf3-11e7-9d9e-bf5a58f15bcf.png)

The promotional currently links to the English Wikipedia page.
_Maybe I should alter that to the equivalent [French](https://fr.wikipedia.org/wiki/Jean-Baptiste_Glaire)  page_ ?
